insert into TAGS (id, TAG, tag_type) values (1, 'современная литература', 1);
insert into TAGS (id, TAG, tag_type) values (2, 'английская литература', 2);
insert into TAGS (id, TAG, tag_type) values (3, 'война', 3);
insert into TAGS (id, TAG, tag_type) values (4, 'экранизировано', 4);
insert into TAGS (id, TAG, tag_type) values (5, 'детская литература', 5);
insert into TAGS (id, TAG, tag_type) values (6, 'книжное путешествие', 1);
insert into TAGS (id, TAG, tag_type) values (7, 'россия', 2);
insert into TAGS (id, TAG, tag_type) values (8, 'франция', 3);
insert into TAGS (id, TAG, tag_type) values (9, 'фэнтези', 4);
insert into TAGS (id, TAG, tag_type) values (10, 'классическая литература', 5);
insert into TAGS (id, TAG, tag_type) values (11, 'любовь', 1);
insert into TAGS (id, TAG, tag_type) values (12, 'мистика', 2);
insert into TAGS (id, TAG, tag_type) values (13, 'немецкая литература', 3);
insert into TAGS (id, TAG, tag_type) values (14, 'флэшмоб 2016', 4);
insert into TAGS (id, TAG, tag_type) values (15, 'books you must read before you die', 5);
insert into TAGS (id, TAG, tag_type) values (16, 'англия', 1);
insert into TAGS (id, TAG, tag_type) values (17, 'вампиры', 2);
insert into TAGS (id, TAG, tag_type) values (18, 'психология', 3);
insert into TAGS (id, TAG, tag_type) values (19, 'рассказы', 4);
insert into TAGS (id, TAG, tag_type) values (20, 'english', 5);
insert into TAGS (id, TAG, tag_type) values (21, 'young adult', 1);
insert into TAGS (id, TAG, tag_type) values (22, 'америка', 2);
insert into TAGS (id, TAG, tag_type) values (23, 'американская литература', 3);
insert into TAGS (id, TAG, tag_type) values (24, 'антиутопия', 4);
insert into TAGS (id, TAG, tag_type) values (25, 'биография', 5);
insert into TAGS (id, TAG, tag_type) values (26, 'дайте две', 1);
insert into TAGS (id, TAG, tag_type) values (27, 'детектив', 2);
insert into TAGS (id, TAG, tag_type) values (28, 'дети', 3);
insert into TAGS (id, TAG, tag_type) values (29, 'детство', 4);
insert into TAGS (id, TAG, tag_type) values (30, 'драма', 5);
insert into TAGS (id, TAG, tag_type) values (31, 'жизнь', 1);
insert into TAGS (id, TAG, tag_type) values (32, 'зарубежная литература', 2);
insert into TAGS (id, TAG, tag_type) values (33, 'история', 3);
insert into TAGS (id, TAG, tag_type) values (34, 'любимое', 4);
insert into TAGS (id, TAG, tag_type) values (35, 'магия', 5);
insert into TAGS (id, TAG, tag_type) values (36, 'приключения', 1);
insert into TAGS (id, TAG, tag_type) values (37, 'роман', 2);
insert into TAGS (id, TAG, tag_type) values (38, 'русская классика', 3);
insert into TAGS (id, TAG, tag_type) values (39, 'русская литература', 4);
insert into TAGS (id, TAG, tag_type) values (40, 'сказка', 5);
insert into TAGS (id, TAG, tag_type) values (41, 'советская литература', 1);
insert into TAGS (id, TAG, tag_type) values (42, 'триллер', 2);
insert into TAGS (id, TAG, tag_type) values (43, 'фантастика', 3);
insert into TAGS (id, TAG, tag_type) values (44, 'философия', 4);
insert into TAGS (id, TAG, tag_type) values (45, 'флэшмоб 2015', 5);
insert into TAGS (id, TAG, tag_type) values (46, 'французская литература', 1);
insert into TAGS (id, TAG, tag_type) values (47, 'художественная литература', 2);
insert into TAGS (id, TAG, tag_type) values (48, 'школьная программа', 3);
insert into TAGS (id, TAG, tag_type) values (49, 'юмор', 4);